use_default_settings: true

plugins:
    searx.plugins.tracker_url_remover.SXNGPlugin:
        active: false

redis:
    url: redis://redis:6379/1

general:
    instance_name: "mcp-search-searxng"
    debug: false

server:
    secret_key: "will-be-overwritten-by-env"
    image_proxy: false

ui:
    default_theme: simple
    default_locale: en

search:
    safe_search: 0
    formats:
        - html
        - json
    suspended_times:
        SearxEngineAccessDenied: 3600

outgoing:
    request_timeout: 5.0
    max_request_timeout: 15.0
    pool_connections: 100
    pool_maxsize: 20
    enable_http2: true

engines:
    - name: duckduckgo
      engine: duckduckgo
      categories: general
      shortcut: ddg

    - name: bing
      engine: bing
      categories: general
      shortcut: b

    - name: google
      engine: google
      categories: general
      shortcut: g

    - name: startpage
      engine: startpage
      categories: general
      shortcut: sp
      disabled: true

    - name: ahmia
      engine: ahmia
      categories: onions
      shortcut: ah
      disabled: true

    - name: wikidata
      engine: wikidata
      categories: general
      shortcut: wd
      disabled: true

    - name: torch
      engine: xpath
      categories: onions
      shortcut: tch

    - name: karmasearch
      engine: karmasearch
      categories: general

    - name: karmasearch videos
      engine: karmasearch
      categories: videos
