ARG IMAGE_NAME
ARG IMAGE_VERSION
FROM ${IMAGE_NAME}:${IMAGE_VERSION}

ARG PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION}
RUN npm install -g playwright@${PLAYWRIGHT_VERSION} && \
    playwright --version && \
    npm cache clean --force

WORKDIR /app

CMD npx -y playwright@${PLAYWRIGHT_VERSION} run-server --port ${PLAYWRIGHT_SERVER_PORT} --host ${PLAYWRIGHT_SERVER_HOST}