ARG IMAGE_NAME
ARG IMAGE_VERSION
FROM ${IMAGE_NAME}:${IMAGE_VERSION}

RUN rm -rf /var/lib/apt/lists/* && \
    rm -f /var/lib/apt/lists/lock /var/cache/apt/archives/lock

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/*
